# Generated by Django 6.0.5 on 2026-05-30 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "poster",
                    models.ImageField(blank=True, null=True, upload_to="movies/"),
                ),
                ("year", models.PositiveIntegerField()),
                ("country", models.CharField(max_length=255)),
                ("world_premiere", models.DateField()),
                ("budget", models.PositiveIntegerField()),
                ("fees_in_usa", models.PositiveIntegerField()),
                ("fees_in_world", models.PositiveIntegerField()),
                (
                    "actors",
                    models.ManyToManyField(related_name="actors", to="movie.actor"),
                ),
                (
                    "directors",
                    models.ManyToManyField(related_name="directors", to="movie.actor"),
                ),
                (
                    "genres",
                    models.ManyToManyField(related_name="g_movies", to="movie.genre"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
